name: push-main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run all make stuff
        run: |
          make clone-dependencies 
          make up-stack
          sleep 15
          make install-goloop
          make create-wallet
          make fund-wallet
