name: push-main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rocksdb
        run: sudo apt-get install librocksdb-dev

      - name: Run all make stuff
        run: make all
